### ISSUE TITLE
where to download  libGeoIP and geoip databases?

### ISSUE THREAD

**Issue by gzliudan** [leafo/luajit-geoip#1]
Hello, leafo:
    Sorry to trouble you again. I want to test luajit-geoip, but don't know where to download or install libGeoIP and geoip databases.

**Comment by leafo** [comment]
This library uses the system installed geoip library, and loads the database from the default path. Generally you should be able to install the geoip library and database through your package manager and it should work.

Note that this library uses v1 of the geoip library. Does your package manager only have v2?

If you need to download the databases directly you can get them here: https://dev.maxmind.com/geoip/legacy/geolite/#Databases

**Comment by gzliudan** [comment]
i use opm command install geoip.

**Comment by gzliudan** [comment]
I find libGeoIP.so, thanks!

**Comment by leafo** [comment]
this is a luajit library that uses the ffi to communicate with a C library. You need to install this c library separately. You might want to invesitgate pure lua implementations if that doesn't work for you
